### ISSUE TITLE
Heat.js doesn't work with strict mode when running RPC mitaka

### ISSUE THREAD

**Issue by evrardjp** [rcbops/horizon-extensions#8]
Hello, 

I think we're gonna need an update to the horizon extensions for mitaka: Horizon has (I guess) an updated angular.js, and we should probably adapt to make it working with strict mode.

Here is the error I see in my browser (FF):
http://paste.openstack.org/show/507588/

I have no knowledge of JS, so I tried to follow this to the letter:
https://docs.angularjs.org/error/$injector/strictdi
This is what I wrote as a result:
https://github.com/evrardjp/horizon-extensions/blob/heat-strict-making/rackspace/static/rackspace/js/heat.js

Ofc it didn't work, so I'd be happy to have guidance/a way to fix this.
Thank you in advance.

Best regards,

**Comment by git-harry** [comment]
This issue has been moved to https://github.com/rcbops/u-suk-dev/issues/207
